INITIAL_POSE = (-2.25, -0.72, 1.5708)

WAYPOINTS = {
    "BASE": (-2.25, -0.72),
    "MAIL_DOOR": (-2.25, -0.30),
    "WEST_HALL": (-2.25, 0.0),
    "OFFICE_HALL": (-0.95, 0.0),
    "OFFICE_DOOR": (-0.95, -0.30),
    "POINT_B": (-0.95, -0.76),
    "ATRIUM_WEST": (-0.55, 0.0),
    "ATRIUM_CENTER": (0.0, 0.0),
    "ATRIUM_EAST": (0.55, 0.0),
    "EAST_HALL": (1.45, 0.0),
    "LAB_HALL": (2.05, 0.0),
    "LAB_DOOR": (2.05, 0.30),
    "POINT_A": (2.05, 0.82),
}

OBSTACLE_AVOIDANCE_ENABLED = False
DELIVERY_POINTS = ["POINT_A", "POINT_B"]
SERVICE_POINTS = ["BASE"] + DELIVERY_POINTS

DEFAULT_DELIVERY_PICKUP = "BASE"
DEFAULT_DELIVERY_DROPOFF = "POINT_A"
DEFAULT_DELIVERY_POINT = DEFAULT_DELIVERY_DROPOFF

DEMO_JOBS_ENABLED = True
DEMO_JOB_PICKUP = "BASE"
DEMO_JOB_DROPOFF = "POINT_B"
DEMO_JOB_TIME_SECONDS = 6.0
DEMO_JOB_PRIORITY = 1

NAV_GRAPH_EDGES = [
    ("BASE", "MAIL_DOOR"),
    ("MAIL_DOOR", "WEST_HALL"),
    ("WEST_HALL", "OFFICE_HALL"),
    ("OFFICE_HALL", "OFFICE_DOOR"),
    ("OFFICE_DOOR", "POINT_B"),
    ("OFFICE_HALL", "ATRIUM_WEST"),
    ("ATRIUM_WEST", "ATRIUM_CENTER"),
    ("ATRIUM_CENTER", "ATRIUM_EAST"),
    ("ATRIUM_EAST", "EAST_HALL"),
    ("EAST_HALL", "LAB_HALL"),
    ("LAB_HALL", "LAB_DOOR"),
    ("LAB_DOOR", "POINT_A"),
]

ARRIVAL_THRESHOLD = 0.14
DELIVERY_ARRIVAL_THRESHOLD = 0.12
BASE_ARRIVAL_THRESHOLD = 0.12
MISSION_TIMEOUT_SECONDS = 180.0
